apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: service-tracking
  name: service-tracking
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-tracking
    spec:
      containers:
      - image: tarikatac/tracking:0.0.1
        name: service-tracking
        resources: {}
        ports:
          - containerPort: 2130
      restartPolicy: Always
status: {}
