apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: service-hall-management
  name: service-hall-management
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-hall-management
    spec:
      containers:
      - image: tarikatac/hallmanagement:0.0.1
        name: service-hall-management
        resources: {}
        ports:
          - containerPort: 2129
      restartPolicy: Always
status: {}
