apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-web
  labels:
    app: service-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-web
  template:
    metadata:
      labels:
        app: service-web
    spec:
      containers:
      - name: service-web
        image: wouterstemgee/front-end:0.0.1
        ports:
        - name: http
          containerPort: 80