apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-food-and-drinks
  labels:
    app: service-food-and-drinks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-food-and-drinks
  template:
    metadata:
      labels:
        app: service-food-and-drinks
    spec:
      containers:
      - name: service-food-and-drinks
        image: thomasdevriese/food-and-drinks:0.0.1
        ports:
        - containerPort: 2125