apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: service-cloakroom
  name: service-cloakroom
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        app: service-cloakroom
    spec:
      containers:
      - image: tarikatac/cloakroom:0.0.1
        name: service-cloakroom
        resources: {}
        ports:
          - containerPort: 2126
      restartPolicy: Always
status: {}
