apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-zookeeper
  labels:
    app: support-zookeeper
    chaos: immune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-zookeeper
  template:
    metadata:
      labels:
        app: support-zookeeper
    spec:
      containers:
      - name: support-zookeeper
        image: confluentinc/cp-zookeeper
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        ports:
        - containerPort: 2181