apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-parkingdb
  labels:
    app: support-parkingdb
    chaos: immune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-parkingdb
  template:
    metadata:
      labels:
        app: support-parkingdb
    spec:
      containers:
      - name: support-parkingdb
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: Parking
        - name: MYSQL_ROOT_PASSWORD
          value: sysdes2
        - name: TZ
          value: Europe/Brussels
        command: ["mysqld --default-authentication-plugin=mysql_native_password"]
        args: []
        ports:
        - containerPort: 3306