apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-kafka
  labels:
    app: support-kafka
    chaos: immune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-kafka
  template:
    metadata:
      labels:
        app: support-kafka
    spec:
      containers:
      - name: support-kafka
        image: confluentinc/cp-kafka
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://support-kafka:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: support-zookeeper:2181
        ports:
        - containerPort: 9092