apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chaos: immune
    app: support-cloakroomdb
  name: support-cloakroomdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        chaos: immune
        app: support-cloakroomdb
    spec:
      containers:
      - args:
        - mongod
        - --port
        - "27017"
        env:
        - name: MONGO_INITDB_DATABASE
          value: cloakroom
        - name: TZ
          value: Europe/Brussels
        image: mongo
        name: support-cloakroomdb
        resources: {}
      restartPolicy: Always
status: {}
