apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\School\J2\sys_design\project\docker\t\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: support-cloakroomdb
  name: support-cloakroomdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: support-cloakroomdb
    spec:
      containers:
      - args:
        - mongod
        - --port
        - "27017"
        env:
        - name: MONGO_INITDB_DATABASE
          value: cloakroom
        - name: TZ
          value: Europe/Brussels
        image: mongo
        name: support-cloakroomdb
        resources: {}
      restartPolicy: Always
status: {}
