apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-multimediadb
  labels:
    app: support-multimediadb
    chaos: immune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-multimediadb
  template:
    metadata:
      labels:
        app: support-multimediadb
    spec:
      containers:
      - name: support-multimediadb
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: messageboard
        - name: MYSQL_ROOT_PASSWORD
          value: sysdes2
        - name: TZ
          value: Europe/Brussels
        ports:
        - containerPort: 3306
