apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-security
  labels:
    app: service-security
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-security
  template:
    metadata:
      labels:
        app: service-security
    spec:
      containers:
      - name: service-security
        image: ebout/security:latest
        ports:
        - containerPort: 2128