apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-event-management
  labels:
    app: service-event-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-event-management
  template:
    metadata:
      labels:
        app: service-event-management
    spec:
      containers:
      - name: service-event-management
        image: wouterstemgee/event-management:latest
        ports:
        - containerPort: 2121