apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-multimedia
  labels:
    app: service-multimedia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-multimedia
  template:
    metadata:
      labels:
        app: service-multimedia
    spec:
      containers:
      - name: service-multimedia
        image: ebout/multimedia:latest
        ports:
        - containerPort: 2127