apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-cloakroom
  name: service-cloakroom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-cloakroom
  template:
    metadata:
      labels:
        app: service-cloakroom
    spec:
      containers:
      - image: tarikatac/cloakroom:latest
        name: service-cloakroom
        ports:
          - containerPort: 2126
