apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ticket
  labels:
    app: service-ticket
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-ticket
  template:
    metadata:
      labels:
        app: service-ticket
    spec:
      containers:
      - name: service-ticket
        image: thomasdevriese/ticket:latest
        ports:
        - containerPort: 2123