apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-event-reservation
  labels:
    app: service-event-reservation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-event-reservation
  template:
    metadata:
      labels:
        app: service-event-reservation
    spec:
      containers:
      - name: service-event-reservation
        image: wouterstemgee/event-reservation:latest
        ports:
        - containerPort: 2120