apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-eventdb
  labels:
    app: support-eventdb
    chaos: immune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-eventdb
  template:
    metadata:
      labels:
        app: support-eventdb
        chaos: immune
    spec:
      containers:
      - name: support-eventdb
        image: mongo
        env:
        - name: TZ
          value: Europe/Brussels
        ports:
        - containerPort: 27017